### ISSUE TITLE
Custom ISO

### ISSUE THREAD

**Issue by dadadadarshan** [ishaan26/config_files#1]
Can you please provide custom installable iso file? 
https://www.youtube.com/watch?v=2JEiP1OYe8E

**Comment by ishaan26** [comment]
I am sorry but i am going to have to say no for this. I really don't mean to be rude or anything but it is a very tedious process and I really don't have time for this. You are free to use the dotfiles provided and if you run into any toruble just hit me up and I'll do my best to help you. I hope you can understand.

I am closing the issue
